### ISSUE TITLE
Newlines whitespace is stripped instead of replaced by a single space

### ISSUE THREAD

**Issue by makeamark1** [xijo/reverse_markdown#34]
It seems that whitespace consisting of newlines only is stripped, instead of being replaced by a single space as expected.

Actual:

```
irb(main):002:0> ReverseMarkdown.convert "hello\nworld\n"
=> "helloworld\n\n"
```

Expected:

```
"hello world\n\n"
```

**Comment by mesge** [comment]
Seeing similar behaviour in `1.0.3` with newlines.

```ruby
convert("<span>Hello\n<\/span><span>World<\/span>")
=> "HelloWorld" (expected 'Hello World')

convert("<p>Hi\n<span>Rami<\/span><\/p>")
=> "HelloWorld\n\n" (expected 'Hello World\n\n')
```

Here's a fiddle for how this HTML would be handled by a browser: https://jsfiddle.net/nkz0oy0z/

These edge cases occur a lot when css is inlined (i.e. email). Any ideas?

**Comment by xijo** [comment]
Hi James, I’m currently traveling without a laptop so I’d get back to you
next week when I have a solid work environment again, ok? 👍

**Comment by manvil** [comment]
Hi @xijo , I know it's been a while for this issue

I see that I am able to reproduce this issue in `2.0.0` as well

```ruby
convert("<span>Hello\n<\/span><span>World<\/span>")
=> "HelloWorld" (expected 'Hello World')

convert("<p>Hello\n<span>World<\/span><\/p>")
=> "HelloWorld\n\n" (expected 'Hello World\n\n')
```

Any suggestions here?

**Comment by subins2000** [comment]
Can confirm, I'm able to reproduce this:

<img width="1218" height="173" alt="Image" src="https://github.com/user-attachments/assets/2093dbaf-d68a-4b0e-8773-f00c2e909fef" />
