### ISSUE TITLE
Emphasis trailing/leading whitespace

### ISSUE THREAD

**Issue by danschultzer** [xijo/reverse_markdown#38]
In relation to #37 I found an issue. It seems there is only proper clearing of whitespace with double emphasis:

    2.1.1 :025 > ReverseMarkdown.convert '<strong> test </strong>'
     => " **test** " 
    2.1.1 :026 > ReverseMarkdown.convert '<em> test </em>'
     => "_ test _"

From reading the `cleaner.rb` file I see that most places the emphasis is only defined as double asterisks, neither single or triple. I suggest that the RegExp is changed to handle this more carefully.

**Comment by xijo** [comment]
@danschultzer I believe your initial problem is long fixed, so I'm closing the issue. Sorry it took so long.

@olance Looking into your issue as well, not sure yet how to solve it..

**Comment by Sija** [comment]
@olance I think source HTML you provided is incorrect, since you can't have `<br>` (block) elements inside `<strong>` (inline) element.

**Comment by olance** [comment]
@Sija nope, this HTML is correct. `<br>` is not a block element as far as I'm aware...

Anyway, the HTML I provided is validated by the W3C validator:

![capture d ecran 2015-11-25 a 09 53 18](https://cloud.githubusercontent.com/assets/314079/11392548/c6b3cb6c-935a-11e5-8451-965e4115331a.png)

**Comment by Sija** [comment]
> **Permitted parent elements**: Any element that accepts [phrasing content](https://developer.mozilla.org/en-US/docs/HTML/Content_categories#Phrasing_content).
> — https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

@olance You're right indeed, thx for correction!

**Comment by olance** [comment]
:)
no worries!
