### ISSUE TITLE
Whitespace before links

### ISSUE THREAD

**Issue by clong-** [xijo/reverse_markdown#56]
When links are directly preceded by non-whitespace characters, a space is added before the link. Hence, a link wrapped in quotes, parens, etc, will come out appearing poorly formatted. Since whitespace is not required before a link in markdown, it shouldn't be added when reversing.

```
irb(main):004:0> ReverseMarkdown.convert '<p>I like this "<a href="http://daringfireball.net/projects/markdown/">markdown</a>" stuff!</p>'
=> "I like this \" [markdown](http://daringfireball.net/projects/markdown/)\" stuff!\n\n"

Expected:
=> "I like this \"[markdown](http://daringfireball.net/projects/markdown/)\" stuff!\n\n"
```

An exception may be where a `!` precedes the link in the HTML, making the converted markdown an inline image instead of a link.

**Comment by benjaminjackson** [comment]
+1
