### ISSUE TITLE
Blockquote not correctly closed

### ISSUE THREAD

**Issue by kanedo** [xijo/reverse_markdown#67]
Hi I have the following HTML:
```html
<blockquote>  This is a quote </blockquote>

<img alt="alt" src="https://path/to/file.jpg" />
```
The generated markdown for this is
```md
> This is a quote ![alt](https://path/to/file.jpg)
```

Somehow the newline before the image is missing after a blockquote. It happens for all blockquote elements I tested that where followed by an image. If there is text after the quote everything works fine.

I'm using reverse_markdown version 1.0.3 and ruby 2.3.1p112

**Comment by xijo** [comment]
@kanedo Thanks, I've just release 1.0.4 to include the change. Sorry for the long wait, I've been a bit busy 😄
