### ISSUE TITLE
Improper space parsing within codeblock

### ISSUE THREAD

**Issue by maestromac** [xijo/reverse_markdown#72]
The use of `String#squeeze` in the file below is messing with codeblock's indentation.
https://github.com/xijo/reverse_markdown/blob/7da325da9ee12b0f68423245f66bf0ce1d76bcc4/lib/reverse_markdown/converters/text.rb#L51
I.E.
```ruby
# Original code block
def original_value
  if assigned?
    original_attribute.original_value
  else
    type_cast(value_before_type_cast)
  end
end

# After ReverseMarkdown
def original_value
 if assigned?
 original_attribute.original_value
 else
 type_cast(value_before_type_cast)
 end
end
```

**Comment by xijo** [comment]
@maestromac Thanks for reporting. Can you provide a complete example of the problem.

The following looks ok for me:

```ruby
code =<<~EOS
  <pre>
    <code>
      def original_value
        if assigned?
          original_attribute.original_value
        else
          type_cast(value_before_type_cast)
        end
      end
    </code>
  </pre>
EOS

puts ReverseMarkdown.convert(code)

        def original_value
          if assigned?
            original_attribute.original_value
          else
            type_cast(value_before_type_cast)
          end
        end
```

**Comment by maestromac** [comment]
It's been a while so I'm having trouble recalling and providing the original item that caused this problem. One thing I do remember is that the code block may not have been wrapped in a pre/code tag. 

Thanks for following up. Since we went ahead and monkey patched that method, I'm closing this issue.
